"""Generate and safely seed the Northwind Finance demo portfolio."""
from __future__ import annotations

import argparse
import asyncio
import json
import os
from dataclasses import asdict, dataclass
from decimal import Decimal
from typing import Any, Iterable

from advisor_core import DecisionEngine
from advisor_core.models import AssessmentInput, AssessmentResult
from pipeline_skills.base import PipelineContext
from pipeline_skills.v2_assessment_skill import run_v2_assessment

from .portfolio import (
    DEMO_BLUEPRINTS,
    DEMO_CREATED_BY,
    DEMO_CUSTOMER_ID,
    DEMO_CUSTOMER_NAME,
    DEMO_VERSION,
    DemoBlueprint,
)


EXPECTED_AWS_CONFIRMATION = "platform-advisor-dev"
DEMO_CUSTOMER_CREATED_AT = "2026-07-28T14:00:00+00:00"
EXPECTED_PANEL_TYPES = (
    "intake",
    "decision_summary",
    "architecture_diagram",
    "requirements",
    "compliance",
    "service_map",
    "risk_cards",
    "phase_timeline",
    "cost_estimate",
    "blueprint",
)


@dataclass
class DemoArtifact:
    definition: DemoBlueprint
    assessment: AssessmentInput
    result: AssessmentResult
    pipeline_ctx: dict[str, Any]
    panels: list[dict[str, Any]]


def _decode_event(event: str) -> dict[str, Any]:
    data_line = next(
        (line[6:] for line in event.splitlines() if line.startswith("data: ")),
        None,
    )
    if not data_line:
        raise ValueError("Pipeline event did not contain an SSE data line")
    return json.loads(data_line)


async def _build_artifact(definition: DemoBlueprint) -> DemoArtifact:
    assessment = definition.assessment()
    result = DecisionEngine().assess(assessment)
    if result.status != "complete" or result.missing_evidence:
        missing = ", ".join(item.field for item in result.missing_evidence)
        raise ValueError(f"{definition.title} is not decision-ready: {missing}")

    ctx = PipelineContext(
        session_id=definition.session_id,
        customer_id=DEMO_CUSTOMER_ID,
    )
    panels: list[dict[str, Any]] = []
    async for raw_event in run_v2_assessment(ctx, assessment, result):
        event = _decode_event(raw_event)
        if event.get("type") != "panel_complete":
            continue
        payload = event["data"]
        panels.append({
            "step": payload["step"],
            "panel_type": payload["panel_type"],
            "data": payload["data"],
        })

    actual_types = tuple(panel["panel_type"] for panel in panels)
    if actual_types != EXPECTED_PANEL_TYPES:
        raise ValueError(
            f"{definition.title} emitted unexpected panels: {actual_types}"
        )
    if ctx.current_step != 10 or not panels[-1]["data"].get("export_ready"):
        raise ValueError(f"{definition.title} did not produce an export-ready blueprint")

    return DemoArtifact(
        definition=definition,
        assessment=assessment,
        result=result,
        pipeline_ctx=asdict(ctx),
        panels=panels,
    )


async def build_demo_portfolio_async() -> list[DemoArtifact]:
    artifacts = [
        await _build_artifact(definition)
        for definition in DEMO_BLUEPRINTS
    ]
    models = {artifact.result.operating_model for artifact in artifacts}
    if models != {"centralized", "federated", "decentralized"}:
        raise ValueError(f"Demo portfolio does not cover all operating models: {models}")
    return artifacts


def build_demo_portfolio() -> list[DemoArtifact]:
    return asyncio.run(build_demo_portfolio_async())


def build_seed_items(artifacts: Iterable[DemoArtifact]) -> list[dict[str, Any]]:
    artifact_list = list(artifacts)
    customer = {
        "PK": f"CUSTOMER#{DEMO_CUSTOMER_ID}",
        "SK": "METADATA",
        "customer_id": DEMO_CUSTOMER_ID,
        "name": DEMO_CUSTOMER_NAME,
        "industry": "Financial Services",
        "contact_email": "platform-demo@northwind.example",
        "notes": (
            "Synthetic demo portfolio generated by the deterministic v2 advisor "
            "engine. No customer data is included."
        ),
        "created_by": DEMO_CREATED_BY,
        "created_at": DEMO_CUSTOMER_CREATED_AT,
        "updated_at": max(
            artifact.definition.created_at for artifact in artifact_list
        ),
        "session_count": len(artifact_list),
        "GSI1PK": "CUSTOMERS",
        "GSI1SK": DEMO_CUSTOMER_CREATED_AT,
        "demo_data": True,
        "demo_version": DEMO_VERSION,
    }
    items: list[dict[str, Any]] = [customer]

    for artifact in artifact_list:
        intake_panel = artifact.panels[0]["data"]
        session = {
            "PK": f"CUSTOMER#{DEMO_CUSTOMER_ID}",
            "SK": f"SESSION#{artifact.definition.session_id}",
            "session_id": artifact.definition.session_id,
            "customer_id": DEMO_CUSTOMER_ID,
            "title": artifact.definition.title,
            "description": artifact.definition.description,
            "status": "complete",
            "current_step": 10,
            "created_by": DEMO_CREATED_BY,
            "created_at": artifact.definition.created_at,
            "updated_at": artifact.definition.created_at,
            "GSI1PK": "SESSIONS",
            "GSI1SK": artifact.definition.created_at,
            "intake_answers": intake_panel["answers"],
            "primary_workload": artifact.assessment.primary_workload.value,
            "recommendation": artifact.result.operating_model,
            "evidence_state": "decision_ready",
            "pipeline_ctx": artifact.pipeline_ctx,
            "demo_data": True,
            "demo_version": DEMO_VERSION,
        }
        items.append(session)
        for panel in artifact.panels:
            items.append({
                "PK": f"SESSION#{artifact.definition.session_id}",
                "SK": f"PANEL#{panel['step']:02d}",
                "session_id": artifact.definition.session_id,
                "step": panel["step"],
                "panel_type": panel["panel_type"],
                "data": panel["data"],
                "updated_at": artifact.definition.created_at,
                "demo_data": True,
                "demo_version": DEMO_VERSION,
            })
    return items


def normalize_for_dynamodb(value: Any) -> Any:
    if isinstance(value, float):
        return Decimal(str(value))
    if isinstance(value, dict):
        return {key: normalize_for_dynamodb(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [normalize_for_dynamodb(item) for item in value]
    return value


def _key(item: dict[str, Any]) -> dict[str, str]:
    return {"PK": item["PK"], "SK": item["SK"]}


def assert_demo_write_scope(table: Any, items: Iterable[dict[str, Any]]) -> None:
    for item in items:
        existing = table.get_item(Key=_key(item), ConsistentRead=True).get("Item")
        if existing and existing.get("demo_data") is not True:
            raise RuntimeError(
                "Refusing to overwrite a non-demo record at "
                f"{item['PK']} / {item['SK']}"
            )


def write_seed_items(table: Any, items: Iterable[dict[str, Any]]) -> int:
    count = 0
    for item in items:
        table.put_item(
            Item=item,
            ConditionExpression="attribute_not_exists(PK) OR demo_data = :demo",
            ExpressionAttributeValues={":demo": True},
        )
        count += 1
    return count


def verify_seed_items(table: Any, items: Iterable[dict[str, Any]]) -> dict[str, int]:
    counts = {"customers": 0, "sessions": 0, "panels": 0}
    for expected in items:
        actual = table.get_item(
            Key=_key(expected),
            ConsistentRead=True,
        ).get("Item")
        if not actual:
            raise RuntimeError(
                f"Seed verification failed for {expected['PK']} / {expected['SK']}"
            )
        if actual.get("demo_version") != DEMO_VERSION:
            raise RuntimeError(
                f"Unexpected demo version at {expected['PK']} / {expected['SK']}"
            )
        if expected["SK"] == "METADATA":
            counts["customers"] += 1
        elif expected["SK"].startswith("SESSION#"):
            counts["sessions"] += 1
        elif expected["SK"].startswith("PANEL#"):
            counts["panels"] += 1
    return counts


def _table_for(args: argparse.Namespace) -> Any:
    import boto3

    if args.target == "local":
        return boto3.resource(
            "dynamodb",
            endpoint_url=args.endpoint,
            region_name=args.region,
            aws_access_key_id="local",
            aws_secret_access_key="local",
        ).Table(args.table)
    return boto3.Session(
        profile_name=args.profile,
        region_name=args.region,
    ).resource("dynamodb").Table(args.table)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=("local", "aws"), default="local")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write the generated records. Without this flag the command is a dry-run.",
    )
    parser.add_argument(
        "--confirm",
        default="",
        help=f"AWS write confirmation; must equal {EXPECTED_AWS_CONFIRMATION}.",
    )
    parser.add_argument("--profile", default="platform-advisor")
    parser.add_argument("--region", default="us-east-1")
    parser.add_argument("--table", default="platform-advisor-main")
    parser.add_argument(
        "--endpoint",
        default=os.environ.get("DYNAMODB_ENDPOINT", "http://localhost:8000"),
    )
    return parser


def main() -> int:
    parser = _parser()
    args = parser.parse_args()
    if (
        args.target == "aws"
        and args.apply
        and args.confirm != EXPECTED_AWS_CONFIRMATION
    ):
        parser.error(
            "AWS writes require "
            f"--confirm {EXPECTED_AWS_CONFIRMATION}"
        )

    artifacts = build_demo_portfolio()
    items = [
        normalize_for_dynamodb(item)
        for item in build_seed_items(artifacts)
    ]
    summary = {
        "customer": DEMO_CUSTOMER_NAME,
        "blueprints": [
            {
                "session_id": artifact.definition.session_id,
                "title": artifact.definition.title,
                "workload": artifact.assessment.primary_workload.value,
                "operating_model": artifact.result.operating_model,
                "panels": len(artifact.panels),
            }
            for artifact in artifacts
        ],
        "records": len(items),
        "target": args.target,
        "table": args.table,
    }
    print(json.dumps(summary, indent=2))
    if not args.apply:
        print("Dry-run complete. No DynamoDB records were written.")
        return 0

    table = _table_for(args)
    assert_demo_write_scope(table, items)
    written = write_seed_items(table, items)
    verified = verify_seed_items(table, items)
    print(f"Wrote and verified {written} fixed demo records: {verified}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
